# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_heros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='real_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
