# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_heros', '0002_hero_real_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='real_name',
        ),
        migrations.AddField(
            model_name='hero',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
